# ----------------------------------------------------------------------------
# Copyright (c) 2016-2020, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

# See style guide: https://github.com/airbnb/javascript
extends: airbnb

# Allow Object spreading to pass linting, otherwise it throws
# Parsing error: Unexpected token ..
parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
# Override a couple of rules because no style guide is perfect.
rules:
    no-alert: off
    comma-dangle: [error, never]
    # PEP8 uses 4 spaces, it's just easier this way.
    indent: [error, 4]
    react/jsx-indent: [error, 4]
    react/jsx-indent-props: [error, 4]
    no-nested-ternary: off
    no-underscore-dangle: off
    react/prop-types: off
    jsx-a11y/no-static-element-interactions: warn
env:
    browser: true
